version: "3.9"

services:
  ollama:
    image: ollama/ollama:${OLLAMA_TAG:-latest}
    env_file:
      - .env
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app
    restart: always

  ollama-setup:
    build: .
    environment:
      - OLLAMA_MODELS=codellama:7b-instruct,wizardcoder:python,deepseek-coder:base
    depends_on:
      - ollama
    networks:
      - app


volumes:
  ollama:

networks:
  app:
