services:
  ollama:
    image: ollama/ollama:${OLLAMA_TAG:-latest}
    env_file:
      - .env
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app
    restart: always

  ollama-setup:
    build: .
    environment:
      - OLLAMA_MODELS=stable-code:3b-code-q4_0
    depends_on:
      - ollama
    networks:
      - app


volumes:
  ollama:

networks:
  app:
